server:
  port: 8084

spring:
  application:
    name: APIGATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USERSERVICE
              uri: lb://USERSERVICE
              predicates:
                - Path=/users/**

            - id: HOTELSERVICE
              uri: lb://HOTELSERVICE
              predicates:
                - Path=/hotels/**,/staffs/**

            - id: RATINGSERVICE
              uri: lb://RATINGSERVICE
              predicates:
                - Path=/ratings/**

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaph2xn5vFmBLrui5d7
            client-secret: nN2G0Anp63FEpjLS2gQ6nVJjWrVhZueUhDCcXK08T9O7H9HRjylNxts8OII2FzLz
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: okta
        provider:
          okta:
            issuer-uri: https://dev-65856828.okta.com/oauth2/default

      resourceserver:
        jwt:
          issuer-uri: https://dev-65856828.okta.com/oauth2/default

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
